---
#--------------------------------------------------
# Make a Backup
#--------------------------------------------------
# TODO convert to postgresql_db commands
- name: "Running {{ complete_backup.script_name }}"
  shell: "./{{ complete_backup.script_name }}"
  args:
    chdir: /root/
  become: true
