---
# tasks file for ansible-role-duplicity
#--------------------------------------------------
# Backup Configuration
#--------------------------------------------------
- name: Install boto3
  pip:
    name: boto3
  when: backupRemoteStorage == "aws_s3"

- name: Generating DB Dump script
  template:
    src:  dump.sh.j2
    dest: "/root/{{ dump_backup_scrip_name }}"
    mode: 0700
    owner: root
    group: root


- name: Backup script
  template:
    src: backup.sh.j2
    dest: "/root/{{ complete_backup_scrip_name }}"
    mode: 0700
    owner: root
    group: root

- name: Create folder where backups are going to be stored
  file:
    path: "{{ backup_dir }}"
    state: directory
    owner: root
    group: root

- name: "Creating script for import from AWS {{ import_aws_scrip_name }}"
  template:
    src: import_backup.sh.j2
    dest: "/root/{{ import_aws_scrip_name }}"
    mode: 0700
    owner: root
    group: root
  when: backupRemoteStorage == "aws_s3"

- name: add cron job to perform dumps of the DB
  cron:
    name: Dump Odoo
    minute: "*/30"
    hour: "7-22"
    job: "/root/{{ dump_backup_scrip_name }}"

- name: add cron job to perform backup
  cron:
    name: Complete Odoo Backup and sent to AWS
    minute: "45"
    hour: "3"
    job: "/root/{{ complete_backup_scrip_name }}"



