---

- name: Install boto3
  pip:
    name: boto3
  when: backupRemoteStorage == "aws_s3"

- name: Generating DB Dump script
  template:
    src:  "{{ dump_backup.template }}"
    dest: "/root/{{ dump_backup.script_name }}"
    mode: 0700
    owner: root
    group: root


- name: Backup script
  template:
    src: "{{ complete_backup.template }}"
    dest: "/root/{{ complete_backup.script_name }}"
    mode: 0700
    owner: root
    group: root

- name: Create folder where backups are going to be stored
  file:
    path: "{{ import_aws_backup.backup_dir }}"
    state: directory
    owner: root
    group: root

- name: "Creating script for import from AWS {{ import_aws_backup.script_name }}"
  template:
    src: "{{ import_aws_backup.template }}"
    dest: "/root/{{ import_aws_backup.script_name }}"
    mode: 0700
    owner: root
    group: root
  when: backupRemoteStorage == "aws_s3"

- name: add cron job to perform dumps of the DB
  cron:
    name: Dump Odoo
    minute: "{{ dump_backup.minute }}"
    hour: "{{ dump_backup.hour }}"
    weekday: "{{ dump_backup.weekday }}"
    job: "/root/{{ dump_backup.script_name }}"

- name: add cron job to perform backup
  cron:
    name: Complete Odoo Backup and sent to AWS
    minute: "{{ complete_backup.minute }}"
    hour: "{{ complete_backup.hour }}"
    job: "/root/{{ complete_backup.script_name }}"



