---
# tasks file for ansible-role-duplicity
#--------------------------------------------------
# Backup Configuration
#--------------------------------------------------
- name: Backup script
  template:
    src: backup.sh.j2
    dest: /root/backup-odoo.sh
    mode: 0700
    owner: root
    group: root

- name: add cron job to perform backup
  cron:
    name: Backup Odoo
    minute: "45"
    hour: "1"
    job: /root/backup-odoo.sh

- name: add cron job to perform backup
  cron:
    name: Backup Odoo 2
    minute: "05"
    hour: "4"
    job: /root/backup-odoo.sh



