---
# tasks file for ansible-role-duplicity
#--------------------------------------------------
# Backup Configuration
#--------------------------------------------------
- name: Install boto3
  pip:
    name: boto3
  when: backupRemoteStorage == "aws_s3"

- name: Backup script
  template:
    src: backup.sh.j2
    dest: "/root/{{ backup_scrip_name }}"
    mode: 0700
    owner: root
    group: root

- name: Create folder where backups are going to be stored
  file:
    path: "{{ backup_dir }}"
    state: directory
    owner: root
    group: root

- name: Restore from AWS script
  template:
    src: restore.sh.j2
    dest: "/root/{{ import_aws_scrip_name }}"
    mode: 0700
    owner: root
    group: root
  when: backupRemoteStorage == "aws_s3"

- name: add cron job to perform backup
  cron:
    name: Backup Odoo
    minute: "45"
    hour: "1"
    job: /root/backup-odoo.sh

- name: add cron job to perform backup
  cron:
    name: Backup Odoo 2
    minute: "05"
    hour: "4"
    job: /root/backup-odoo.sh



