---
# TODO separate role raw-server in different tasks files to be able to call from testing without create users
- name: Converge
  hosts: all
  tasks:
    # - name: "Include ansible-raw-server"
    #   import_tasks: "../../../ansible-role-raw-server/tasks/packages.yml"

    - name: "Include ansible-role-duplicity"
      include_role:
        name: "ansible-role-duplicity"
      vars:
        molecule_testing: true
        odoo_version: "14.0"
        db_user: odoo
        backup_time: "202021"
        import_aws_backup:
          template: import_backup.sh.j2
          script_name: import_backup.sh
          backup_dir: "/opt/odoo/"
